### ISSUE TITLE
Warn after dying in the void

### ISSUE THREAD

**Issue by rafalohaki** [funkemunky/Kauri#60]
version client/server 1.19
When i jumped into a void:
```
[03:03:12] [Server thread/INFO]: [Matrix] (Via) Player rafalohaki joined with (1.19.x/759) client
[03:03:36] [Kauri Logging Threads/INFO]: [Dev] [Kauri] rafalohaki flagged Block (C) (x1.0) (Beta)
[03:03:45] [Server thread/INFO]: rafalohaki fell out of the world
[03:03:46] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[03:03:46] [Server thread/WARN]: 	at Kauri-2.19.jar//dev.brighten.anticheat.processing.PacketProcessor.processServer(PacketProcessor.java:609)
[03:03:46] [Server thread/WARN]: 	at Kauri-2.19.jar//dev.brighten.anticheat.processing.PacketProcessor.lambda$new$3(PacketProcessor.java:67)
[03:03:46] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[03:03:46] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[03:03:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[03:03:46] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Could not find method in DimensionManager with name a
[03:03:46] [Server thread/WARN]: 	at Atlas.jar//cc.funkemunky.api.reflections.types.WrappedClass.getMethod(WrappedClass.java:206)
[03:03:46] [Server thread/WARN]: 	at Atlas.jar//cc.funkemunky.api.tinyprotocol.packet.out.WrappedOutRespawnPacket.<clinit>(WrappedOutRespawnPacket.java:92)
[03:03:46] [Server thread/WARN]: 	... 5 more
```
second time i jumped:
```
[03:06:27] [Server thread/INFO]: rafalohaki fell out of the world
[03:06:30] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.tinyprotocol.packet.out.WrappedOutRespawnPacket
[03:06:30] [Server thread/WARN]: 	at Kauri-2.19.jar//dev.brighten.anticheat.processing.PacketProcessor.processServer(PacketProcessor.java:609)
[03:06:30] [Server thread/WARN]: 	at Kauri-2.19.jar//dev.brighten.anticheat.processing.PacketProcessor.lambda$new$3(PacketProcessor.java:67)
[03:06:30] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[03:06:30] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[03:06:30] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by funkemunky** [comment]
We have temporary revoked support for 1.19 to give time for working on new changes. Logging for things to fix/
