### ISSUE TITLE
Plugin loading Error

### ISSUE THREAD

**Issue by Zsomi** [funkemunky/Kauri#68]
Minecraft version: 1.18.2-Purpur-1632
Plugin version: 2.19.2
Atlas version: 1.12.1.1

Error:

[13:52:20 ERROR]: Error occurred while enabling Kauri v2.19.2 (Is it up to date?)
java.lang.NoClassDefFoundError: cc/funkemunky/api/utils/Color
        at dev.brighten.anticheat.Kauri.onEnable(Kauri.java:79) ~[Kauri-2.19.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: cc.funkemunky.api.utils.Color
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
[13:52:20 INFO]: [Kauri] Disabling Kauri v2.19.2
[13:52:20 ERROR]: Error occurred while disabling Kauri v2.19.2 (Is it up to date?)
java.lang.NoClassDefFoundError: cc/funkemunky/api/utils/MiscUtils
        at dev.brighten.anticheat.Kauri.unload(Kauri.java:92) ~[Kauri-2.19.2.jar:?]
        at dev.brighten.anticheat.Kauri.onDisable(Kauri.java:87) ~[Kauri-2.19.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: cc.funkemunky.api.utils.MiscUtils
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more

**Comment by Matt-MX** [comment]
I also have a similar error on start up.

**Comment by Matt-MX** [comment]
Bump?

**Comment by tt-thoma** [comment]
Paper 1.21.1 - build 119
Fresh, first start

**Plugins:**
- [GriefPrevention 16.18.4](https://dev.bukkit.org/projects/grief-prevention/files/5471866)
- [Atlas 1.12.1.1](https://github.com/funkemunky/Atlas/releases/tag/1.12.1.1)
- [API 2.19.2](https://github.com/funkemunky/Kauri/releases/tag/2.19.2)
- [Detections 2.19.2](https://github.com/funkemunky/Kauri/releases/tag/2.19.2)
- [Impl 2.19.2](https://github.com/funkemunky/Kauri/releases/tag/2.19.2)

_Kauri has other errors, see full logs at the bottom_

**Error enabling Atlas**
```
[14:08:56 INFO]: [Atlas] Enabling Atlas v1.12.1.1
[14:08:56 ERROR]: Error occurred while enabling Atlas v1.12.1.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at Atlas.jar/cc.funkemunky.api.reflections.impl.MinecraftReflection.<clinit>(MinecraftReflection.java:34) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at Atlas.jar/cc.funkemunky.api.reflections.Reflections.<clinit>(Reflections.java:44) ~[Atlas.jar:?]
        ... 17 more
[14:08:56 INFO]: [Atlas] Disabling Atlas v1.12.1.1
[14:08:56 ERROR]: Error occurred while disabling Atlas v1.12.1.1
java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.utils.MiscUtils
        at Atlas.jar/cc.funkemunky.api.Atlas.alog(Atlas.java:495) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.alog(Atlas.java:488) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.onDisable(Atlas.java:174) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at Atlas.jar/cc.funkemunky.api.reflections.impl.MinecraftReflection.<clinit>(MinecraftReflection.java:34) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.utils.MiscUtils.<clinit>(MiscUtils.java:97) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:238) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.loadConfig(Atlas.java:230) ~[Atlas.jar:?]
        at Atlas.jar/cc.funkemunky.api.Atlas.onEnable(Atlas.java:109) ~[Atlas.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        ... 10 more
```

**Error enabling Kauri**
```
[14:08:57 INFO]: [Kauri] Enabling Kauri v2.19.2
[14:08:57 ERROR]: Error occurred while enabling Kauri v2.19.2 (Is it up to date?)
java.lang.NoClassDefFoundError: cc/funkemunky/api/utils/Color
        at Impl-2.19.2.jar/dev.brighten.anticheat.Kauri.onEnable(Kauri.java:79) ~[Impl-2.19.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: cc.funkemunky.api.utils.Color
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
[14:08:57 INFO]: [Kauri] Disabling Kauri v2.19.2
[14:08:57 ERROR]: Error occurred while disabling Kauri v2.19.2
java.lang.NoClassDefFoundError: cc/funkemunky/api/utils/MiscUtils
        at Impl-2.19.2.jar/dev.brighten.anticheat.Kauri.unload(Kauri.java:92) ~[Impl-2.19.2.jar:?]
        at Impl-2.19.2.jar/dev.brighten.anticheat.Kauri.onDisable(Kauri.java:87) ~[Impl-2.19.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: cc.funkemunky.api.utils.MiscUtils
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 17 more
```

Full logs: https://mclo.gs/sMhzyym

**Comment by tt-thoma** [comment]
This problem is not new - I don't get how the creator takes so much time fixing it...
Maybe it's really complicated, or it would require rewriting of the entire system, but it's sad bc that ac looked really good
