### ISSUE TITLE
KAURI ERROR (Velocity)

### ISSUE THREAD

**Issue by Vazzzx** [funkemunky/Kauri#70]
Hello, I would like to use kauri in bungeecord mode, but neither Atlas is loading in Velocity

[09:38:22 ERROR]: Unable to load plugin plugins/Kauri-2.19.2.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file Kauri-2.19.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:61) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]

**Comment by gabrielsilvavieira** [comment]
@Vazzzx 
`The plugin file Kauri-2.19.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord  #plugins.`

**Comment by Izibane** [comment]
> Hello, I would like to use kauri in bungeecord mode, but neither Atlas is loading in Velocity
> 
> [09:38:22 ERROR]: Unable to load plugin plugins/Kauri-2.19.2.jar com.velocitypowered.api.plugin.InvalidPluginException: The plugin file Kauri-2.19.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins. at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)] at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:61) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)] at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)] at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)] at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)] at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[Velocity.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]

use a real server software like spigot
